# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: Hockey21!
      MARIADB_DATABASE: color-guessing-game-db
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
